name: Publish release
on:
  release:
    types: [created]
    
permissions:
 contents: read
 packages: write
 
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
         distribution: "liberica"
         java-version: '11'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build & Publish
        run: ./gradlew -Pversion=${{ github.event.release.tag_name }} build publish --info --stacktrace
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ github.token }}
